### ISSUE TITLE
Using newer versions of packages in image

### ISSUE THREAD

**Issue by chauhankaranraj** [thoth-station/s2i-tensorflow-notebook#43]
**Description**
Hey team,

In the [Pipfile](https://github.com/thoth-station/s2i-tensorflow-notebook/blob/master/Pipfile#L8) for this image, `pandas` has been pinned to `0.25.*`, which is ~1 year old. There's been a major release since then, with some [breaking changes](https://pandas.pydata.org/docs/whatsnew/v1.0.0.html#backwards-incompatible-api-changes). Is there a specific reason for pinning it down to `0.25.*`?

Some other packages (`statsmodels`, `matplotlib`, etc) are also pinned to older versions. Was this for compatibility reasons or could we use the updated packages?

**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Replace `==` with `>=` in Pipfile

**Describe alternatives you've considered**
Manually install newer packages after JupyterHub pod is spawned with this image

**Comment by harshad16** [comment]
Thanks for opening the issue.
we had pinned it down with respect to the upstream project requirements for s2i-tensorflow-notebook, https://github.com/jupyter-on-openshift/jupyter-notebooks/blob/develop/tensorflow-notebook/requirements.txt
Being said that, we should definitely update our images with updated packages if that would help the users.
we would check with thoth advise and see when the package would be stable.
will take this up, this week and check on the relevant updates :+1:
