### ISSUE TITLE
Not able to install Tensorflow 2.4

### ISSUE THREAD

**Issue by altruistcoder** [thoth-station/s2i-tensorflow-notebook#66]
Hello @harshad16 

I was trying to create s2i-tensorflow-notebook using this repository with a change that I needed to install **Tensorflow 2.4** along with some other updated dependencies. I have attached the updated Pipfile for your reference and I also had to delete the *"Pipfile.lock"* as I was facing some errors. I previously installed Tensorflow 2.2 with this approach and that worked fine but now I am facing the below error while installing the Tensorflow version 2.4:

![image](https://user-images.githubusercontent.com/31319270/111512601-ece0a200-8775-11eb-9c48-cf3ab9cd6ebb.png)

I tried adding **grpcio** module in the Pipfile with various versions such as  grpcio="*" and grpcio="==1.32.0" but it is still not working in any case.

Can you please help me in solving this error as I am stuck in this.
[Pipfile.txt](https://github.com/thoth-station/s2i-tensorflow-notebook/files/6158455/Pipfile.txt)

**Comment by harshad16** [comment]
Hello @altruistcoder 
i have look at this and respond

**Comment by goern** [comment]
@altruistcoder did you try to do a `thamos advise` in your fork? have a look at https://www.youtube.com/watch?v=P4k-ELGq13Q

/kind question
Cc: @fridex

**Comment by harshad16** [comment]
as @goern  suggested you can use our tool called `thamos advise`
it is a cli tool for our resolver which would return you pinned result help with the issue.
documentation: https://github.com/thoth-station/thamos#thamos


the issue occuring in the provided stack is due to the transitive requirements of package `seldon-core` and `tensorflow`
grpcio is the one as you pointed. 
```
  grpcio==1.32.0 (from -r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 7))
  grpcio<2.0,>=1.1.3 (from grpcio-opentracing==1.1.4->seldon-core==1.6.0->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 30))
  grpcio<2.0.0 (from seldon-core==1.6.0->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 30))
  grpcio>=1.24.3 (from tensorboard==2.4.1->tensorflow==2.4.1->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 35))
  grpcio>=1.34.1 (from grpcio-reflection==1.34.1->seldon-core==1.6.0->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 30))
  grpcio~=1.32.0 (from tensorflow==2.4.1->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 35))
```
from the above we can see that `grpcio-reflection==1.34.1` has a requirement of >= 1.34.1 grpcio , that what clashes with tensorflow requirement of grpcio `~=1.32.0`
```
  grpcio>=1.34.1 (from grpcio-reflection==1.34.1->seldon-core==1.6.0->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 30))
  grpcio~=1.32.0 (from tensorflow==2.4.1->-r /tmp/pipenvf5cg0ni5requirements/pipenv-g5fsyy39-constraints.txt (line 35))
```

one of solution would be to pin the `grpcio-reflection= "==1.32.0"` which would inturn fix the grpcio issue.

**Comment by altruistcoder** [comment]
Thanks a lot @harshad16 for providing such a quick response. It worked!

Also, thanks @goern for providing the reference to "thamos". I'll definitely check it out.

**Comment by harshad16** [comment]
Glad to know the solution works for you.
I will go ahead and close the issue. 

please do try our tool `thamos` , if you have any question regarding thoth advice or come across any issue while using our tool thamos, please don't hesitate to reach out. Feedback is key :)
