### ISSUE TITLE
meta information mismatsch

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-tensorflow-notebook#67]
**Describe the bug**
something in the image meta information is inconsistent.

**To Reproduce**
1. Go to https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-jupyterhub/imagestreamtags/s2i-tensorflow-notebook%3Av0.0.2

**Expected behavior**
info is in sync...

**Screenshots**
![image](https://user-images.githubusercontent.com/260331/111610171-56df6280-87db-11eb-9e31-0a04fca3b4e5.png)

**Additional context**
n/a

/kind bug
/sig build
/sig user-experience
/assign @harshad16

**Comment by harshad16** [comment]
thanks for being thorough and pointing this out.

**Comment by goern** [comment]
any update on this?
